HOSTS:
  el7-server:
    roles:
      - server
      - default
      - master
      - elasticsearch_server
      - el7
    platform:   el-7-x86_64
    box:        puppetlabs/centos-7.0-64-nocm
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
    hypervisor: vagrant
    yum_repos:
      simp:
        baseurl: https://dl.bintray.com/simp/5.1.X
        gpgcheck: 0
      elasticsearch:
        baseurl: 'https://packages.elastic.co/elasticsearch/2.x/centos'
        gpgcheck: 0

  el6-server:
    roles:
      - elasticsearch_server
      - el6
    platform:   el-6-x86_64
    box:        puppetlabs/centos-6.6-64-nocm
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-6.6-64-nocm
    hypervisor: vagrant
    yum_repos:
      simp:
        baseurl: https://dl.bintray.com/simp/4.2.X
        gpgcheck: 0
      elasticsearch:
        baseurl: 'https://packages.elastic.co/elasticsearch/2.x/centos'
        gpgcheck: 0

CONFIG:
  log_level: verbose
  type:      foss
  vagrant_memsize: 512
  # vb_gui: true
